version: "3.2"
services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - "./private/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/app/public"
    depends_on:
      - php
      - db
    links:
      - php
      - db
    environment:
      VIRTUAL_HOST: dac.docker

  php:
    build: ./private/docker/php
    restart: always
    volumes:
       - "./private/docker/php/php.ini:/usr/local/etc/php/php.ini"
       - "./public:/var/www/app/public"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp

